In [1]:
import pandas as pd

In [2]:
import json
import pandas as pd

with open('Hotel-json/HotelList.json', encoding='utf-8-sig') as f:
    data = json.load(f)

df = pd.json_normalize(data['Hotels'])
print(df.shape)
df.head()

(15585, 46)

,HotelID,HotelLicenseNumber,HotelName,AlternateNames,Description,PositionLat,PositionLon,Geometry,HotelClasses,HotelStars,...,ParkingSpaces,CheckTimes,Remarks,UpdateTime,PostalAddress.City,PostalAddress.CityCode,PostalAddress.Town,PostalAddress.TownCode,PostalAddress.ZipCode,PostalAddress.StreetAddress
0,Hotel_A15010000H_000008,南投縣民宿358號,Siyuan Ju Homestay,[],Bed and Breakfast in Nantou County,23.935199,120.970365,None,[4],0,...,0,None,,2025-04-28T16:11:27+08:00,Nantou County,10008,Puli Township,10008020,545,"No.1, Shuitou Rd., Puli Township, Nantou Count..."
1,Hotel_A15010000H_000015,臺東縣旅館103號,Triumph Shinjuku Business Travel,[],This business hotel is located in the center o...,22.751340,121.151420,None,[3],0,...,0,None,,2026-01-24T17:58:52+08:00,Taitung County,10014,Taitung City,10014010,950,"No.243, Fujian Rd., Taitung City, Taitung Coun..."
2,Hotel_A15010000H_000018,臺東縣民宿1214號,Guanguan Xianghu Homestay,[],Homestay located in Taitung,23.052510,121.161910,None,[4],0,...,0,None,,2026-01-15T09:55:03+08:00,Taitung County,10014,Guanshan Township,10014030,956,"No.28, Bade Rd., Guanshan Township, Taitung Co..."
3,Hotel_A15010000H_000019,臺東縣民宿1135號,Kepler Bed and Breakfast,[],"A simple, two-story building with a gray and c...",22.904173,121.127894,None,[4],0,...,0,None,,2025-02-27T09:47:18+08:00,Taitung County,10014,Luye Township,10014050,955,"No.20, Ln. 112, Long 3rd Rd., Luye Township, T..."
4,Hotel_A15010000H_000020,宜蘭縣民宿1331號,Woo Shiba House,[],"Bed and Breakfast in Yilan – Woo Shiba House, ...",24.685754,121.797620,None,[4],0,...,2,None,,2025-07-14T09:06:52+08:00,Yilan County,10002,Wujie Township,10002090,268,"Aly. 5, Ln. 559, Sec. 2, Wujie Central Rd., Wu..."

In [3]:
df = df[df['HotelLicenseNumber'].str.contains('臺北市', na=False)]
print(df.shape)
df

(583, 46)

,HotelID,HotelLicenseNumber,HotelName,AlternateNames,Description,PositionLat,PositionLon,Geometry,HotelClasses,HotelStars,...,ParkingSpaces,CheckTimes,Remarks,UpdateTime,PostalAddress.City,PostalAddress.CityCode,PostalAddress.Town,PostalAddress.TownCode,PostalAddress.ZipCode,PostalAddress.StreetAddress
16,Hotel_A15010000H_000045,臺北市旅館567號,Green World ZhongXiao,[],"Taipei, the crucial confluence of internationa...",25.041257,121.542775,None,[3],0,...,35,None,,2025-04-30T14:31:37+08:00,Taipei City,63000,Daan District,63000030,106,"No.180, Sec. 4, Zhongxiao E. Rd., Da’an Dist.,..."
32,Hotel_A15010000H_000077,臺北市旅館274號,URTRIP HOTEL,[],Hotel located in Taipei City,25.048339,121.544923,None,[3],0,...,0,None,,2025-10-27T10:46:59+08:00,Taipei City,63000,Songshan District,63000010,105,"12F., No.219, Sec. 2, Chang’an E. Rd., Songsha..."
81,Hotel_A15010000H_000188,臺北市旅館231號,LIO HOTEL XIMEN,[],Hotel located in Taipei City,25.043652,121.504065,None,[3],0,...,0,None,,2025-07-23T11:42:24+08:00,Taipei City,63000,Wanhua District,63000070,108,"2-4F., No.4-6, Aly. 36, Ln. 25, Kangding Rd., ..."
97,Hotel_A15010000H_000232,臺北市旅館082號,Guide Hotel Taipei NTU,[],Li Yuan Hotel is located in Taipei’s culturall...,25.021508,121.526892,None,[3],0,...,0,None,,2025-08-29T11:59:35+08:00,Taipei City,63000,Zhongzheng District,63000050,100,"1-8F., No.98, Sec. 3, Roosevelt Rd., Zhongzhen..."
122,Hotel_A15010000H_000278,臺北市旅館544號,VIA HOTEL ZHONGXIAO,[],Hotel located in Taipei City,25.043137,121.541006,None,[3],0,...,0,None,,2025-02-27T10:06:57+08:00,Taipei City,63000,Daan District,63000030,106,"3F., No.1, Ln. 126, Sec. 1, Fuxing S. Rd., Da’..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15320,Hotel_A15010000H_038495,臺北市旅館815號,Hotel Uketamo,[],.,25.040346,121.543994,None,[3],0,...,100,None,,2026-01-23T13:56:06+08:00,Taipei City,63000,Daan District,63000030,106,"No.191,Sec.1,Fuxing S.Rd.,Da& #39;an Dist.,Tai..."
15396,Hotel_A15010000H_038630,臺北市旅館816號,EverStar Hotel,[],Hotels in Taipei City,25.050524,121.524711,None,[3],0,...,4,None,,2026-02-09T17:25:51+08:00,Taipei City,63000,Zhongshan District,63000040,104,"2F, No. 98, Linsen N. Rd., Zhongshan Dist.； 3 ..."
15520,Hotel_A15010000H_038852,臺北市旅館818號,Wowhappy-ximen Hotel,[],-,25.043140,121.505310,None,[3],0,...,0,None,,2026-03-31T16:30:50+08:00,Taipei City,63000,Wanhua District,63000070,108,"6 F. 5 F., No. 81, Chengdu Rd., Wanhua Dist., ..."
15567,Hotel_A15010000H_038954,臺北市旅館820號,YMS by onefifteen,[],.,25.105100,121.525900,None,[3],0,...,0,None,,2026-04-20T10:53:03+08:00,Taipei City,63000,Shilin District,63000110,111,"No. 8, Jianye Rd., Shilin Dist., Taipei City 1..."
15568,Hotel_A15010000H_038955,臺北市旅館821號,YMS by onefifteen-Area2,[],.,25.135800,121.546900,None,[3],0,...,0,None,,2026-04-20T10:40:03+08:00,Taipei City,63000,Shilin District,63000110,111,"No. 1、No.3, Jianye Rd., Shilin Dist., Taipei C..."

In [4]:
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
df

,HotelID,HotelLicenseNumber,HotelName,AlternateNames,Description,PositionLat,PositionLon,Geometry,HotelClasses,HotelStars,TaiwanHost,HotelCertificationMarks,Telephones,Images,Organizations,ServiceTimeInfo,TrafficInfo,ParkingInfo,Facilities,ServiceStatus,PaymentMethods,LocatedCities,WebsiteURL,ReservationURLs,MapURLs,SameAsURLs,SocialMediaURLs,RoomInfo,ServiceInfo,TotalRooms,LowestPrice,CeilingPrice,TotalCapacity,AccessibleRooms,Toilets,LiftingEquipments,ParkingSpaces,CheckTimes,Remarks,UpdateTime,PostalAddress.City,PostalAddress.CityCode,PostalAddress.Town,PostalAddress.TownCode,PostalAddress.ZipCode,PostalAddress.StreetAddress
16,Hotel_A15010000H_000045,臺北市旅館567號,Green World ZhongXiao,[],"Taipei, the crucial confluence of internationa...",25.041257,121.542775,None,[3],0,0,[],[{'Tel': '(02)27116869'}],"[{'Name': '行政雙床房', 'Description': '', 'URL': '...","[{'Name': '洛碁實業股份有限公司', 'Class': 'Operator', '...",,,Parking Space:Car 35、Motorcycle 0、Truck 0,[],1,[],[],http://zhongxiao.greenworldhotels.com,[],[],[],[],Double10000;Single10000;Single(Assessible room...,"restaurant,meeting room,Wi-Fi,National travel ...",150,3000,28000,340,0,0,0,35,None,,2025-04-30T14:31:37+08:00,Taipei City,63000,Daan District,63000030,106,"No.180, Sec. 4, Zhongxiao E. Rd., Da’an Dist.,..."
32,Hotel_A15010000H_000077,臺北市旅館274號,URTRIP HOTEL,[],Hotel located in Taipei City,25.048339,121.544923,None,[3],0,0,[],[{'Tel': '(02)27752277'}],[],"[{'Name': '悠趣旅館股份有限公司', 'Class': 'Operator', '...",,,Parking Space:Car 0、Motorcycle 0、Truck 0,[],1,[],[],,[],[],[],[],,,27,10000,15000,68,0,0,0,0,None,,2025-10-27T10:46:59+08:00,Taipei City,63000,Songshan District,63000010,105,"12F., No.219, Sec. 2, Chang’an E. Rd., Songsha..."
81,Hotel_A15010000H_000188,臺北市旅館231號,LIO HOTEL XIMEN,[],Hotel located in Taipei City,25.043652,121.504065,None,[3],0,0,[],[{'Tel': '(02)23889855'}],[],"[{'Name': '萬龍大旅社', 'Class': 'Operator', 'TaxCo...",,,Parking Space:Car 0、Motorcycle 0、Truck 0,[],1,[],[],http://www.liohotel.com.tw/,[],[],[],[],,Bike friendly accommodation,17,800,3000,31,0,0,0,0,None,,2025-07-23T11:42:24+08:00,Taipei City,63000,Wanhua District,63000070,108,"2-4F., No.4-6, Aly. 36, Ln. 25, Kangding Rd., ..."
97,Hotel_A15010000H_000232,臺北市旅館082號,Guide Hotel Taipei NTU,[],Li Yuan Hotel is located in Taipei’s culturall...,25.021508,121.526892,None,[3],0,0,[],[{'Tel': '(02)23657367'}],"[{'Name': '家庭客房(Family Room)', 'Description': ...","[{'Name': '雀客國際酒店股份有限公司', 'Class': 'Operator',...",,,Parking Space:Car 0、Motorcycle 0、Truck 0,[],1,[],[],,[],[],[],[],Suite5960;Double4360;Double4560;Double5460;Dou...,"Internet,parking lot,,,,",35,13800,18800,70,0,0,0,0,None,,2025-08-29T11:59:35+08:00,Taipei City,63000,Zhongzheng District,63000050,100,"1-8F., No.98, Sec. 3, Roosevelt Rd., Zhongzhen..."
122,Hotel_A15010000H_000278,臺北市旅館544號,VIA HOTEL ZHONGXIAO,[],Hotel located in Taipei City,25.043137,121.541006,None,[3],0,0,[],[{'Tel': '(02)77116368'}],[],"[{'Name': '英屬維京群島商丰韻股份有限公司', 'Class': 'Operato...",,,Parking Space:Car 0、Motorcycle 0、Truck 0,[],1,[],[],,[],[],[],[],,,21,2420,20000,50,0,0,0,0,None,,2025-02-27T10:06:57+08:00,Taipei City,63000,Daan District,63000030,106,"3F., No.1, Ln. 126, Sec. 1, Fuxing S. Rd., Da’..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15320,Hotel_A15010000H_038495,臺北市旅館815號,Hotel Uketamo,[],.,25.040346,121.543994,None,[3],0,0,[],[{'Tel': '(02)27319888'}],[],"[{'Name': '福泰國際旅館管理顧問股份有限公司', 'Class': 'Operat...",,,Parking Space:Car 100、Motorcycle 0、Truck 0,[],1,[],[],http://www.hoteluketamo.com,[],[],[],[],,,97,6600,43890,250,0,0,0,100,None,,2026-01-23T13:56:06+08:00,Taipei City,63000,Daan District,63000030,106,"No.191,Sec.1,Fuxing S.Rd.,Da& #39;an Dist.,Tai..."
15396,Hotel_A15010000H_038630,臺北市旅館816號,EverStar Hotel,[],Hotels in Taipei City,25.050524,121.524711,None,[3],0,0,[],[{'Tel': '(02)66099999'}],[],"[{'Name': '金慶國際股份有限公司', 'Class': 'Operator', '...",,,Parking Space:Car 4、Motorcycle 0、Truck 0,[],1,[],[],https://TaipeiEverStar.com,[],[],[],[],,,6,15000,20000,13,0,0,0,4,None,,2026-02-09T17:25:51+08:00,Taipei City,63000,Zhongshan District,63000040,104,"2F, No. 98, Linsen N. Rd., Zhongshan Dist.； 3 ..."
15520,Hotel_A15010000H_038852,臺北市旅館818號,Wowhappy-ximen Hotel,[],-,25.043140,121.505310,None,[3],0,0,[],"[{'Tel': '(02)23616682'}, {'Tel': '0919306737'}]",[],"[{'Name': '賜禧有限公司', 'Class': 'Operator', 'TaxC...",,,Parking Space:Car 0、Motorcycle 0、Truck 0,[],1,[],[],https://wowhappy-ximen.com.tw/,[],[],[],[],,,58,12000,12000,192,0,0,0,0,None,,2026-03-31T16:30:50+08:00,Taipei City,63000,Wanhua District,63000070,108,"6 F. 5 F., No. 81, Chengdu Rd., Wanhua Dist., ..."
15567,Hotel_A15010000H_038954,臺北市旅館820號,YMS by onefifteen,[],.,25.105100,121.525900,None,[3],0,0,[],"[{'Tel': '(02)28618880'}, {'Tel': '0933026323'}]",[],"[{'Name': '香港商初食股份有限公司台灣分公司', 'Class': 'Operat...",,,Parking Space:Car 0、Motorcycle 0、Truck 0,[],1,[],[],https://ymsbyonefifteen.com/,[],[],[],[],,,3,60000,104500,6,0,0,0,0,None,,2026-04-20T10:53:03+08:00,Taipei City,63000,Shilin District,63000110,111,"No. 8, Jianye Rd., Shilin Dist., Taipei City 1..."
15568,Hotel_A15010000H_038955,臺北市旅館821號,YMS by onefifteen-Area2,[],.,25.135800,121.546900,None,[3],0,0,[],[{'Tel': '(02)28618880'}],[],"[{'Name': '香港商初食股份有限公司台灣分公司', 'Class': 'Operat...",,,Parking Space:Car 0、Motorcycle 0、Truck 0,[],1,[],[],https://ymsbyonefifteen.com,[],[],[],[],,,7,25000,50000,14,0,0,0,0,None,,2026-04-20T10:40:03+08:00,Taipei City,63000,Shilin District,63000110,111,"No. 1、No.3, Jianye Rd., Shilin Dist., Taipei C..."

In [5]:
df = df.drop(columns=['AlternateNames', 'Description', 'Geometry', 'HotelStars', 'TaiwanHost', 'HotelCertificationMarks', 'Images', 'ServiceTimeInfo', 'TrafficInfo', 'Facilities', 'PaymentMethods','LocatedCities', 'ReservationURLs' , 'MapURLs', 'SameAsURLs' , 'SocialMediaURLs', 'RoomInfo', 'CheckTimes','Remarks','UpdateTime'])

In [6]:
df = df.drop(columns=['Toilets', 'LiftingEquipments'])
df.head()

,HotelID,HotelLicenseNumber,HotelName,PositionLat,PositionLon,HotelClasses,Telephones,Organizations,ParkingInfo,ServiceStatus,WebsiteURL,ServiceInfo,TotalRooms,LowestPrice,CeilingPrice,TotalCapacity,AccessibleRooms,ParkingSpaces,PostalAddress.City,PostalAddress.CityCode,PostalAddress.Town,PostalAddress.TownCode,PostalAddress.ZipCode,PostalAddress.StreetAddress
16,Hotel_A15010000H_000045,臺北市旅館567號,Green World ZhongXiao,25.041257,121.542775,[3],[{'Tel': '(02)27116869'}],"[{'Name': '洛碁實業股份有限公司', 'Class': 'Operator', '...",Parking Space:Car 35、Motorcycle 0、Truck 0,1,http://zhongxiao.greenworldhotels.com,"restaurant,meeting room,Wi-Fi,National travel ...",150,3000,28000,340,0,35,Taipei City,63000,Daan District,63000030,106,"No.180, Sec. 4, Zhongxiao E. Rd., Da’an Dist.,..."
32,Hotel_A15010000H_000077,臺北市旅館274號,URTRIP HOTEL,25.048339,121.544923,[3],[{'Tel': '(02)27752277'}],"[{'Name': '悠趣旅館股份有限公司', 'Class': 'Operator', '...",Parking Space:Car 0、Motorcycle 0、Truck 0,1,,,27,10000,15000,68,0,0,Taipei City,63000,Songshan District,63000010,105,"12F., No.219, Sec. 2, Chang’an E. Rd., Songsha..."
81,Hotel_A15010000H_000188,臺北市旅館231號,LIO HOTEL XIMEN,25.043652,121.504065,[3],[{'Tel': '(02)23889855'}],"[{'Name': '萬龍大旅社', 'Class': 'Operator', 'TaxCo...",Parking Space:Car 0、Motorcycle 0、Truck 0,1,http://www.liohotel.com.tw/,Bike friendly accommodation,17,800,3000,31,0,0,Taipei City,63000,Wanhua District,63000070,108,"2-4F., No.4-6, Aly. 36, Ln. 25, Kangding Rd., ..."
97,Hotel_A15010000H_000232,臺北市旅館082號,Guide Hotel Taipei NTU,25.021508,121.526892,[3],[{'Tel': '(02)23657367'}],"[{'Name': '雀客國際酒店股份有限公司', 'Class': 'Operator',...",Parking Space:Car 0、Motorcycle 0、Truck 0,1,,"Internet,parking lot,,,,",35,13800,18800,70,0,0,Taipei City,63000,Zhongzheng District,63000050,100,"1-8F., No.98, Sec. 3, Roosevelt Rd., Zhongzhen..."
122,Hotel_A15010000H_000278,臺北市旅館544號,VIA HOTEL ZHONGXIAO,25.043137,121.541006,[3],[{'Tel': '(02)77116368'}],"[{'Name': '英屬維京群島商丰韻股份有限公司', 'Class': 'Operato...",Parking Space:Car 0、Motorcycle 0、Truck 0,1,,,21,2420,20000,50,0,0,Taipei City,63000,Daan District,63000030,106,"3F., No.1, Ln. 126, Sec. 1, Fuxing S. Rd., Da’..."

In [7]:
df['HotelName'].iloc[-1]

'YMS by onefifteen-Area2'

In [8]:
#df.to_json('Taipei_Hotel.json', orient='records', force_ascii=False, indent=2)

In [9]:
from gmaps_fetcher import search_by_name, fetch_reviews, fetch_photo_urls
from tqdm import tqdm

SAMPLE = 5 # set to None to run all rows

def enrich(row):
    place = search_by_name(row['HotelName'], region='台北')
    if not place or not place.get('place_id'):
        return pd.Series({
            'chinese_name': None,
            'gmaps_url': None,
            'review_summary': None,
            'top_pics': None,
        })

    pid = place['place_id']
    reviews = fetch_reviews(pid, sort='most_relevant')
    summary = ' | '.join(r['text'] for r in reviews[:3] if r.get('text'))
    pics = fetch_photo_urls(pid, max_photos=5)

    return pd.Series({
        'place_id': place.get('place_id'),
        'chinese_name': place.get('name'),
        'gmaps_url': place.get('google_maps_url'),
        'review_summary': summary or None,
        'top_pics': pics or None,
    })



target = df.head(SAMPLE) if SAMPLE else df
tqdm.pandas(desc='Enriching')
enriched = target.progress_apply(enrich, axis=1)

df_enriched = target.join(enriched)
df_enriched

Enriching: 100%|██████████| 5/5 [00:08<00:00,  1.75s/it]

,HotelID,HotelLicenseNumber,HotelName,PositionLat,PositionLon,HotelClasses,Telephones,Organizations,ParkingInfo,ServiceStatus,WebsiteURL,ServiceInfo,TotalRooms,LowestPrice,CeilingPrice,TotalCapacity,AccessibleRooms,ParkingSpaces,PostalAddress.City,PostalAddress.CityCode,PostalAddress.Town,PostalAddress.TownCode,PostalAddress.ZipCode,PostalAddress.StreetAddress,place_id,chinese_name,gmaps_url,review_summary,top_pics
16,Hotel_A15010000H_000045,臺北市旅館567號,Green World ZhongXiao,25.041257,121.542775,[3],[{'Tel': '(02)27116869'}],"[{'Name': '洛碁實業股份有限公司', 'Class': 'Operator', '...",Parking Space:Car 35、Motorcycle 0、Truck 0,1,http://zhongxiao.greenworldhotels.com,"restaurant,meeting room,Wi-Fi,National travel ...",150,3000,28000,340,0,35,Taipei City,63000,Daan District,63000030,106,"No.180, Sec. 4, Zhongxiao E. Rd., Da’an Dist.,...",ChIJ3y1qn8WrQjQRT2SCMGiSng8,洛碁大飯店 忠孝館 Green World ZhongXiao,https://maps.google.com/?cid=1125497933077308495,房間隔音不好，隔壁洗澡放水的聲音轟轟轟的很明顯，窗外也是，救護車、喧鬧聲都聽得到，暖氣機只有...,[https://lh3.googleusercontent.com/places/ANXA...
32,Hotel_A15010000H_000077,臺北市旅館274號,URTRIP HOTEL,25.048339,121.544923,[3],[{'Tel': '(02)27752277'}],"[{'Name': '悠趣旅館股份有限公司', 'Class': 'Operator', '...",Parking Space:Car 0、Motorcycle 0、Truck 0,1,,,27,10000,15000,68,0,0,Taipei City,63000,Songshan District,63000010,105,"12F., No.219, Sec. 2, Chang’an E. Rd., Songsha...",ChIJ1ULSQtyrQjQR0cRPSmp72Ec,台北悠趣旅店 (小巨蛋館),https://maps.google.com/?cid=5177023468105876689,我訂9天雙人床有窗的房型，\n房間其實蠻不錯的，\n以這個價為來說我覺得滿意度很高，\n還有...,[https://lh3.googleusercontent.com/places/ANXA...
81,Hotel_A15010000H_000188,臺北市旅館231號,LIO HOTEL XIMEN,25.043652,121.504065,[3],[{'Tel': '(02)23889855'}],"[{'Name': '萬龍大旅社', 'Class': 'Operator', 'TaxCo...",Parking Space:Car 0、Motorcycle 0、Truck 0,1,http://www.liohotel.com.tw/,Bike friendly accommodation,17,800,3000,31,0,0,Taipei City,63000,Wanhua District,63000070,108,"2-4F., No.4-6, Aly. 36, Ln. 25, Kangding Rd., ...",ChIJeZqzlAipQjQRvhIhSeSfLsM,力歐時尚旅館-西門館,https://maps.google.com/?cid=14064354489152901822,因房間冷氣完全不冷，且牆上冷氣遙控器無法調整溫度，於是向櫃台反映問題。結果，沒想到櫃台一位年...,[https://lh3.googleusercontent.com/places/ANXA...
97,Hotel_A15010000H_000232,臺北市旅館082號,Guide Hotel Taipei NTU,25.021508,121.526892,[3],[{'Tel': '(02)23657367'}],"[{'Name': '雀客國際酒店股份有限公司', 'Class': 'Operator',...",Parking Space:Car 0、Motorcycle 0、Truck 0,1,,"Internet,parking lot,,,,",35,13800,18800,70,0,0,Taipei City,63000,Zhongzheng District,63000050,100,"1-8F., No.98, Sec. 3, Roosevelt Rd., Zhongzhen...",ChIJg7wMgf2pQjQRNyH3UgpKvzg,承攜行旅 - 台北台大館,https://maps.google.com/?cid=4089068394877755703,櫃檯一位中年男性！服務態度極差！\n當天因帶家人前往，較早到飯店，櫃檯人員告知，還不能入住！...,[https://lh3.googleusercontent.com/places/ANXA...
122,Hotel_A15010000H_000278,臺北市旅館544號,VIA HOTEL ZHONGXIAO,25.043137,121.541006,[3],[{'Tel': '(02)77116368'}],"[{'Name': '英屬維京群島商丰韻股份有限公司', 'Class': 'Operato...",Parking Space:Car 0、Motorcycle 0、Truck 0,1,,,21,2420,20000,50,0,0,Taipei City,63000,Daan District,63000030,106,"3F., No.1, Ln. 126, Sec. 1, Fuxing S. Rd., Da’...",ChIJ3T3jGNqrQjQRuuUr0YnIpEM,丰居旅店-忠孝館,https://maps.google.com/?cid=4874241190967109050,4人房型很大，乾淨明亮，浴廁乾淨，住宿地點方便，附近鄰近忠孝復興捷運站，旁邊晚上可以逛遼寧夜...,[https://lh3.googleusercontent.com/place-photo...

In [12]:
import os
from google import genai
from gmaps_fetcher import fetch_reviews

gemini = genai.Client(api_key=os.environ['GEMINI_API_KEY'])

def summarize_reviews(reviews: list[dict]) -> str | None:
    texts = [r['text'] for r in reviews if r.get('text')]
    if not texts:
        return None

    joined = '\n---\n'.join(texts)
    prompt = (
        "以下是某間飯店的 Google 評論。請用 2-3 句繁體中文總結整體住客體驗，"
        "包含優點與缺點，避免逐條重複，僅輸出摘要本身：\n\n"
        f"{joined}"
    )

    resp = gemini.models.generate_content(
        model='gemini-2.5-flash',
        contents=prompt,
    )
    return resp.text.strip() if resp.text else None

KeyError: 'GEMINI_API_KEY'

In [ ]:
from tqdm import tqdm
tqdm.pandas(desc='Summarising')

def llm_summary(row):
    place = search_by_name(row['HotelName'], region='台北')
    if not place or not place.get('place_id'):
        return None
    reviews = fetch_reviews(place['place_id'], sort='most_relevant')
    return summarize_reviews(reviews)

df_enriched['review_summary'] = df_enriched.progress_apply(llm_summary, axis=1)
df_enriched[['HotelName', 'chinese_name', 'review_summary']].head()

In [1]:
import os
from gmaps_fetcher._config import GOOGLE_MAPS_API_KEY
from gmaps_fetcher import search_by_name
import httpx

print("Key loaded:", bool(GOOGLE_MAPS_API_KEY), "len=", len(GOOGLE_MAPS_API_KEY))
print("CWD:", os.getcwd())

# Direct API call so we see the raw error
resp = httpx.get(
    "https://maps.googleapis.com/maps/api/place/textsearch/json",
    params={"query": "台北君悅酒店", "key": GOOGLE_MAPS_API_KEY, "language": "zh-TW"},
    timeout=10,
)
print("HTTP:", resp.status_code)
print(resp.json())

Key loaded: True len= 39
CWD: /Users/emilyliao/Desktop/YTP
HTTP: 200
{'html_attributions': [], 'results': [{'business_status': 'OPERATIONAL', 'formatted_address': '110061台灣臺北市信義區松壽路2號', 'geometry': {'location': {'lat': 25.0351708, 'lng': 121.5628669}, 'viewport': {'northeast': {'lat': 25.0368996302915, 'lng': 121.5639368302915}, 'southwest': {'lat': 25.0342016697085, 'lng': 121.5612388697085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png', 'icon_background_color': '#909CE1', 'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet', 'name': 'Grand Hyatt Taipei', 'photos': [{'height': 2218, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/116221685949306313275">Grand Hyatt Taipei</a>'], 'photo_reference': 'AU_ZVEGAWMinNuQ7Oe0cPaurBFCLCdmscWnl2CjIjTvjT4bQF9vywh4Rr6-d6CASCtYTjMrlaIOesPOq2-g3ll8i-ISTZfLcBCbNAJ5fBfta0fTxrBs_e8raTVEqB7MK50coiCRyFGjEJ7ebyzbSPhG-8Y_I7JMxpGQpYEGlvsHnjU_X2ZiRU_x7wnoI68QzVGQ-1n6EiahzjKkciuHhArGvgugte2FjtGfhT74VredrQurSLjfde1r8849_rYg1GSVSh29pE8YE-K0FI6t1VHiry3qhc-tAyFfZ9zeJmeorwoJMiA', 'width': 2879}], 'place_id': 'ChIJty1ap7erQjQRWmO-mTv1zkQ', 'plus_code': {'compound_code': '2HP7+34 台灣臺北市信義區西村里', 'global_code': '7QQ32HP7+34'}, 'rating': 4.4, 'reference': 'ChIJty1ap7erQjQRWmO-mTv1zkQ', 'types': ['establishment', 'lodging', 'point_of_interest'], 'user_ratings_total': 15411}, {'business_status': 'OPERATIONAL', 'formatted_address': '110台灣臺北市信義區', 'geometry': {'location': {'lat': 25.035194, 'lng': 121.5634}, 'viewport': {'northeast': {'lat': 25.0365478802915, 'lng': 121.5647531302915}, 'southwest': {'lat': 25.03384991970849, 'lng': 121.5620551697085}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png', 'icon_background_color': '#7B9EB0', 'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/generic_pinlet', 'name': '台北君悅酒店', 'photos': [{'height': 4032, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101609536418991812548">A kaur</a>'], 'photo_reference': 'AU_ZVEHqcf0hw2XLuSoXqaSKNPSS-cV8RxTGq26vhQ6KDIXNUQAdtFqqU8dv5Dn-SKpIATdIUZuY8YokliBn4OaflOHaIDcdX66Wy7Q7SZa4J9e04h4yiKZJYcFIkS9L-TQ2KxGyeTUyk9yaV0ll7_zM3x0iRd6gf4Q-mtKytDmiwidAmmObPkugWg7N4lZbEf5G-6ZBWxL-Ty2r3dhMRUCnz8XFekxG7GGmTxEHIG00va3oFYtyC0pBDkGGH7rUaxwbHKep_uJCDg7n05ihmWA07QLrgjnoF9Pafi8DfMnfx9N64l5QuCsXzlJFi6xhim7L13HkvSG-duy_xidIlgXJbjTR2eXvhTqFXrjWXoFE0HrIb46br0KQrnEi_cVNbbXN5Sc7pV3mki83jBFco39kuTryDyzlQpmpyWFj655BSSLjzX1L', 'width': 3024}], 'place_id': 'ChIJQcc4BberQjQR7PqCOm6tXTs', 'plus_code': {'compound_code': '2HP7+39 台灣臺北市信義區西村里', 'global_code': '7QQ32HP7+39'}, 'rating': 4, 'reference': 'ChIJQcc4BberQjQR7PqCOm6tXTs', 'types': ['establishment', 'point_of_interest', 'transit_station'], 'user_ratings_total': 143}], 'status': 'OK'}

In [12]:
from gmaps_fetcher import search_by_name

for _, row in df.head(5).iterrows():
    place = search_by_name(row['HotelName'], region='台北')
    print(f"{row['HotelName']!r}")
    print(f"  -> name: {place.get('name') if place else None!r}")
    print(f"  -> place_id: {place.get('place_id') if place else None}")
    print()

'Green World ZhongXiao'
  -> name: '洛碁大飯店 忠孝館 Green World ZhongXiao'
  -> place_id: ChIJ3y1qn8WrQjQRT2SCMGiSng8

'URTRIP HOTEL'
  -> name: '台北悠趣旅店 (小巨蛋館)'
  -> place_id: ChIJ1ULSQtyrQjQR0cRPSmp72Ec

'LIO HOTEL XIMEN'
  -> name: '力歐時尚旅館-西門館'
  -> place_id: ChIJeZqzlAipQjQRvhIhSeSfLsM

'Guide Hotel Taipei NTU'
  -> name: '承攜行旅 - 台北台大館'
  -> place_id: ChIJg7wMgf2pQjQRNyH3UgpKvzg

'VIA HOTEL ZHONGXIAO'
  -> name: '丰居旅店-忠孝館'
  -> place_id: ChIJ3T3jGNqrQjQRuuUr0YnIpEM

In [ ]:
import os
from dotenv import load_dotenv
load_dotenv()
print('Maps:', bool(os.environ.get('GOOGLE_MAPS_API_KEY')))
print('Gemini:', bool(os.environ.get('GEMINI_API_KEY')))